# Generated by Django 4.2.4 on 2023-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumb",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
